//
// Created by magnus on 10/12/22.
//

#include "Viewer/Tools/Macros.h"

DISABLE_WARNING_PUSH
DISABLE_WARNING_TYPE_LIMITS
DISABLE_WARNING_MISSING_INITIALIZERS
DISABLE_WARNING_CAST_QUALIFIERS
DISABLE_WARNING_DOUBLE_PROMOTION
#define STB_IMAGE_IMPLEMENTATION
#include "stb_image.h"

#define STB_IMAGE_WRITE_IMPLEMENTATION
#include "stb_image_write.h"
DISABLE_WARNING_POP
